package com.dbychkov.data.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dbychkov.data.greendao.LessonEntity;
import com.dbychkov.data.greendao.FlashcardEntity;

import com.dbychkov.data.greendao.LessonEntityDao;
import com.dbychkov.data.greendao.FlashcardEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lessonEntityDaoConfig;
    private final DaoConfig flashcardEntityDaoConfig;

    private final LessonEntityDao lessonEntityDao;
    private final FlashcardEntityDao flashcardEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lessonEntityDaoConfig = daoConfigMap.get(LessonEntityDao.class).clone();
        lessonEntityDaoConfig.initIdentityScope(type);

        flashcardEntityDaoConfig = daoConfigMap.get(FlashcardEntityDao.class).clone();
        flashcardEntityDaoConfig.initIdentityScope(type);

        lessonEntityDao = new LessonEntityDao(lessonEntityDaoConfig, this);
        flashcardEntityDao = new FlashcardEntityDao(flashcardEntityDaoConfig, this);

        registerDao(LessonEntity.class, lessonEntityDao);
        registerDao(FlashcardEntity.class, flashcardEntityDao);
    }
    
    public void clear() {
        lessonEntityDaoConfig.getIdentityScope().clear();
        flashcardEntityDaoConfig.getIdentityScope().clear();
    }

    public LessonEntityDao getLessonEntityDao() {
        return lessonEntityDao;
    }

    public FlashcardEntityDao getFlashcardEntityDao() {
        return flashcardEntityDao;
    }

}
