package com.dbychkov.data.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.dbychkov.data.greendao.FlashcardEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FLASHCARDS.
*/
public class FlashcardEntityDao extends AbstractDao<FlashcardEntity, Long> {

    public static final String TABLENAME = "FLASHCARDS";

    /**
     * Properties of entity FlashcardEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Word = new Property(1, String.class, "word", false, "WORD");
        public final static Property Definition = new Property(2, String.class, "definition", false, "DEFINITION");
        public final static Property Status = new Property(3, int.class, "status", false, "STATUS");
        public final static Property LessonId = new Property(4, Long.class, "lessonId", false, "LESSON_ID");
    };

    private DaoSession daoSession;

    private Query<FlashcardEntity> lessonEntity_FlashcardEntityListQuery;

    public FlashcardEntityDao(DaoConfig config) {
        super(config);
    }
    
    public FlashcardEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FLASHCARDS' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'WORD' TEXT NOT NULL ," + // 1: word
                "'DEFINITION' TEXT NOT NULL ," + // 2: definition
                "'STATUS' INTEGER NOT NULL ," + // 3: status
                "'LESSON_ID' INTEGER);"); // 4: lessonId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FLASHCARDS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FlashcardEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getWord());
        stmt.bindString(3, entity.getDefinition());
        stmt.bindLong(4, entity.getStatus());
 
        Long lessonId = entity.getLessonId();
        if (lessonId != null) {
            stmt.bindLong(5, lessonId);
        }
    }

    @Override
    protected void attachEntity(FlashcardEntity entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FlashcardEntity readEntity(Cursor cursor, int offset) {
        FlashcardEntity entity = new FlashcardEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // word
            cursor.getString(offset + 2), // definition
            cursor.getInt(offset + 3), // status
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // lessonId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FlashcardEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setWord(cursor.getString(offset + 1));
        entity.setDefinition(cursor.getString(offset + 2));
        entity.setStatus(cursor.getInt(offset + 3));
        entity.setLessonId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FlashcardEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FlashcardEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "flashcardEntityList" to-many relationship of LessonEntity. */
    public List<FlashcardEntity> _queryLessonEntity_FlashcardEntityList(Long lessonId) {
        synchronized (this) {
            if (lessonEntity_FlashcardEntityListQuery == null) {
                QueryBuilder<FlashcardEntity> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.LessonId.eq(null));
                lessonEntity_FlashcardEntityListQuery = queryBuilder.build();
            }
        }
        Query<FlashcardEntity> query = lessonEntity_FlashcardEntityListQuery.forCurrentThread();
        query.setParameter(0, lessonId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getLessonEntityDao().getAllColumns());
            builder.append(" FROM FLASHCARDS T");
            builder.append(" LEFT JOIN LESSONS T0 ON T.'LESSON_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected FlashcardEntity loadCurrentDeep(Cursor cursor, boolean lock) {
        FlashcardEntity entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        LessonEntity lessonEntity = loadCurrentOther(daoSession.getLessonEntityDao(), cursor, offset);
        entity.setLessonEntity(lessonEntity);

        return entity;    
    }

    public FlashcardEntity loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<FlashcardEntity> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<FlashcardEntity> list = new ArrayList<FlashcardEntity>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<FlashcardEntity> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<FlashcardEntity> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
